import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Yassir Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Image src="/images/logo.svg" alt='Yassir' width={400} height={200}></Image>
        <h1 className={styles.title}>
          Welcome to <Link href="/home">Yassir Services!</Link>
        </h1>

        <p className={styles.description}>
          A place where you can offer or request a service
        </p>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>Offer a service &rarr;</h2>
            <p>You&rsquo;re a professional. and you want to offer your services</p>
          </a>

          <a className={styles.card}>
            <h2>Request a service &rarr;</h2>
            <p>You&rsquo;re looking for a professional<br/><br/></p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a>
          Yassir {' '}
          Hackathon
        </a>
      </footer>
    </div>
  )
}
